"""CLI UI components — Rich-based display helpers."""

from .console import (
    console,
    print_banner,
    print_section,
    print_header,
    print_subheader,
    print_divider,
    print_dot_divider,
    print_success,
    print_step,
    print_wizard_step,
    print_suggested_next,
    print_phase,
    print_bar,
    print_tree,
    print_tree_item,
    print_tree_pipe,
    print_funnel,
    print_breakdown,
    print_sample_row,
    print_metric_line,
    print_kv,
    print_comment,
    print_boxed,
)
from .errors import show_error, show_warning, show_info
from .progress import (
    create_extraction_progress,
    create_enrichment_progress,
    create_scoring_progress,
    create_action_progress,
    create_simple_progress,
)
from .tables import (
    make_status_table,
    make_extract_status_table,
    make_pipeline_status_table,
    make_cleanup_preview_table,
    make_sample_table,
    make_summary_table,
)
from . import theme

__all__ = [
    "console",
    "print_banner",
    "print_section",
    "print_header",
    "print_subheader",
    "print_divider",
    "print_dot_divider",
    "print_success",
    "print_step",
    "print_wizard_step",
    "print_suggested_next",
    "print_phase",
    "print_funnel",
    "print_breakdown",
    "print_sample_row",
    "print_metric_line",
    "print_kv",
    "print_comment",
    "print_bar",
    "print_tree",
    "print_tree_item",
    "print_tree_pipe",
    "print_boxed",
    "show_error",
    "show_warning",
    "show_info",
    "create_extraction_progress",
    "create_enrichment_progress",
    "create_scoring_progress",
    "create_action_progress",
    "create_simple_progress",
    "make_status_table",
    "make_extract_status_table",
    "make_pipeline_status_table",
    "make_cleanup_preview_table",
    "make_sample_table",
    "make_summary_table",
    "theme",
]
